import constants from '../../utils/constants';
import schemaConstants from '../../utils/schemaConstants';

export const ProductData = [
  {
    id: constants.slimFitCottonShirtId,
    brand: constants.zara,
    name: constants.slimFitCottonShirtName,
    price: schemaConstants.SLIM_FIT_COTTON_SHIRT_PRICE,
    colour: constants.blue,
    category: constants.categoryMen,
    quantity: schemaConstants.MIN_QUANTITY,
    description: constants.clothingDescription,
    image: constants.slimFitCottonShirtName,
    size: null,
    totalPrice: schemaConstants.MIN_TOTALPRICE,
    sizeAvailable: [constants.small, constants.medium, constants.large],
  },
  {
    id: constants.cottonPoloShirtId,
    brand: constants.nike,
    name: constants.cottonPoloShirtName,
    price: schemaConstants.COTTON_SHIRT_PRICE,
    colour: constants.white,
    quantity: schemaConstants.MIN_QUANTITY,
    description: constants.clothingDescription,
    image: constants.cottonPoloShirtImage,
    category: constants.categoryMen,
    size: null,
    totalPrice: schemaConstants.MIN_TOTALPRICE,
    sizeAvailable: [constants.small, constants.medium, constants.large],
  },
  {
    id: constants.fitShirtId,
    brand: constants.zara,
    name: constants.fitShirtName,
    price: schemaConstants.FIT_SHIRT_PRICE,
    colour: constants.maroon,
    quantity: schemaConstants.MIN_QUANTITY,
    description: constants.clothingDescription,
    image: constants.slimFitCottonShirtName,
    category: constants.categoryMen,
    size: null,
    totalPrice: schemaConstants.MIN_TOTALPRICE,
    sizeAvailable: [constants.small, constants.medium, constants.large],
  },
  {
    id: constants.shortSleeveId,
    brand: constants.nike,
    name: constants.shortSleeveName,
    price: schemaConstants.SLIM_FIT_COTTON_SHIRT_PRICE,
    colour: constants.blue,
    quantity: schemaConstants.MIN_QUANTITY,
    description: constants.clothingDescription,
    image: constants.slimFitCottonShirtName,
    category: constants.categoryMen,
    size: null,
    totalPrice: schemaConstants.MIN_TOTALPRICE,
    sizeAvailable: [constants.small, constants.medium, constants.large],
  },
  {
    id: constants.adidasMenTshitId,
    brand: constants.adidas,
    name: constants.adidasTshitName,
    price: schemaConstants.ADIDAS_TSHIRT,
    colour: constants.black,
    quantity: schemaConstants.MIN_QUANTITY,
    description: constants.clothingDescription,
    image: constants.adidasMenTshitImage,
    category: constants.categoryMen,
    size: null,
    totalPrice: schemaConstants.MIN_TOTALPRICE,
    sizeAvailable: [constants.small, constants.medium, constants.large],
  },

  {
    id: constants.cottonShirtWomenId,
    brand: constants.zara,
    name: constants.slimFitCottonShirtImage,
    price: schemaConstants.SLIM_FIT_COTTON_SHIRT_PRICE,
    colour: constants.blue,
    size: null,
    quantity: schemaConstants.MIN_QUANTITY,
    description: constants.clothingDescription,
    image: constants.cottonShirtWomenImage,
    category: constants.categoryWomen,
    totalPrice: schemaConstants.MIN_TOTALPRICE,
    sizeAvailable: [constants.small, constants.medium, constants.large],
  },
  {
    id: constants.poloWomenShirtId,
    brand: constants.nike,
    name: constants.poloWomenShirtName,
    price: schemaConstants.COTTON_SHIRT_PRICE,
    colour: constants.white,
    quantity: schemaConstants.MIN_QUANTITY,
    description: constants.clothingDescription,
    image: constants.poloWomenShirtImage,
    category: constants.categoryWomen,
    totalPrice: schemaConstants.MIN_TOTALPRICE,
    sizeAvailable: [constants.small, constants.medium, constants.large],
    size: null,
  },
  {
    id: constants.pinkShirtId,
    brand: constants.zara,
    name: constants.pinkShirtName,
    price: schemaConstants.FIT_SHIRT_PRICE,
    colour: constants.pink,
    size: null,
    quantity: schemaConstants.MIN_QUANTITY,
    description: constants.clothingDescription,
    image: constants.pinkShirtImage,
    category: constants.categoryWomen,
    totalPrice: schemaConstants.MIN_TOTALPRICE,
    sizeAvailable: [constants.small, constants.medium, constants.large],
  },
  {
    id: constants.womenSleeveShirtId,
    brand: constants.nike,
    name: constants.womenSleeveShirtName,
    price: schemaConstants.SLIM_FIT_COTTON_SHIRT_PRICE,
    colour: constants.blue,
    size: null,
    quantity: schemaConstants.MIN_QUANTITY,
    description: constants.clothingDescription,
    image: constants.womenSleeveShirtImage,
    category: constants.categoryWomen,
    totalPrice: schemaConstants.MIN_TOTALPRICE,
    sizeAvailable: [constants.small, constants.medium, constants.large],
  },
  {
    id: constants.womenAdidasShirtId,
    brand: constants.adidas,
    name: constants.adidasTshitName,
    price: schemaConstants.ADIDAS_TSHIRT,
    colour: constants.black,
    size: null,
    quantity: schemaConstants.MIN_QUANTITY,
    description: constants.clothingDescription,
    image: constants.womenAdidasShirtImage,
    category: constants.categoryWomen,
    totalPrice: schemaConstants.MIN_TOTALPRICE,
    sizeAvailable: [constants.small, constants.medium, constants.large],
  },
  {
    id: constants.wirelessMouseId,
    brand: constants.logi,
    name: constants.wirelessMouseName,
    price: schemaConstants.WIRELESS_MOUSE_PRICE,
    colour: constants.black,
    quantity: schemaConstants.MIN_QUANTITY,
    description: constants.wirelessMouseDescription,
    image: constants.wirelessMouseImage,
    category: constants.categoryElectronics,
    totalPrice: schemaConstants.MIN_TOTALPRICE,
  },
  {
    id: constants.routerId,
    brand: constants.tpLink,
    name: constants.routerName,
    price: schemaConstants.ROUTER_PRICE,
    colour: constants.blue,
    quantity: schemaConstants.MIN_QUANTITY,
    description: constants.routerDescription,
    image: constants.routerImage,
    category: constants.categoryElectronics,
    totalPrice: schemaConstants.MIN_TOTALPRICE,
  },
  {
    id: constants.keyBoardId,
    brand: constants.dell,
    name: constants.keyboardName,
    price: schemaConstants.KEYBOARD_PRICE,
    colour: constants.black,
    quantity: schemaConstants.MIN_QUANTITY,
    description: constants.keyboardDescription,
    image: constants.keyboardImage,
    category: constants.categoryElectronics,
    totalPrice: schemaConstants.MIN_TOTALPRICE,
  },
  {
    id: constants.webcamId,
    brand: constants.logi,
    name: constants.webcamName,
    price: schemaConstants.WEBCAM_PRICE,
    colour: constants.black,
    quantity: schemaConstants.MIN_QUANTITY,
    description: constants.webcamDescription,
    image: constants.webcamImage,
    category: constants.categoryElectronics,
    totalPrice: schemaConstants.MIN_TOTALPRICE,
  },
  {
    id: constants.deskpadId,
    brand: constants.ikarus,
    name: constants.deskpadName,
    price: schemaConstants.DESKPAD_PRICE,
    colour: constants.brown,
    quantity: schemaConstants.MIN_QUANTITY,
    description: constants.deskpadDescription,
    image: constants.deskpadImage,
    category: constants.categoryElectronics,
    totalPrice: schemaConstants.MIN_TOTALPRICE,
  },
];
