const constants = {
  home: 'Home',
  homePath: '/',
  navLogo: 'Fill-o-Cart',
  navDropDownTitle: 'Products',
  navClassname: 'mr-auto',
  cartIcon: 'fas fa-shopping-cart',
  navToggle: 'basic-navbar-nav',
  welcomeMessage: 'Welcome to Fill-o-Cart',
  phoneNumber: '9855446622',
  mobileIcon: 'fas fa-mobile',
  menClothing: `Men's Clothing`,
  menClothingPath: '/mens-clothings',
  womenClothing: `Women's Clothing`,
  womenClothingPath: '/womens-clothings',
  electronics: 'Electronics',
  electronicsPath: '/electronics',
  price: 'Price : $',
  addToCart: 'Add to cart',
  productSliceName: 'product',
  cartSliceName: 'cart',
  productListing: 'listing',
  filter: 'Filter',
  addedToCart: 'Your item is added to the cart',
  successAlert: 'success',
};
export default constants;
