const constants = {
  home: 'Home',
  homePath: '/',
  navLogo: 'Fill-o-Cart',
  navDropDownTitle: 'Products',
  navClassname: 'mr-auto',
  cartIcon: 'fas fa-shopping-cart',
  navToggle: 'basic-navbar-nav',
  welcomeMessage: 'Welcome to Fill-o-Cart',
  phoneNumber: '9855446622',
  mobileIcon: 'fas fa-mobile',
  menClothing: `Men's Clothing`,
  menClothingPath: '/mens-clothings',
  womenClothing: `Women's Clothing`,
  womenClothingPath: '/womens-clothings',
  electronics: 'Electronics',
  electronicsPath: '/electronics',
  price: 'Price : $',
  addToCart: 'Add to cart',
  productSliceName: 'product',
  cartSliceName: 'cart',
  productListing: 'listing',
  filter: 'Filter',
  addedToCart: 'Your item is added to the cart',
  successAlert: 'success',
  small: 'small',
  medium: 'medium',
  large: 'large',
  zara: 'Zara',
  nike: 'Nike',
  adidas: 'Adidas',
  logi: 'Logi',
  dell: 'Dell',
  tpLink: 'TP-Link',
  ikarus: 'IKARUS',
  blue: 'Blue',
  black: 'Black',
  pink: 'Pink',
  white: 'White',
  brown: 'Brown',
  maroon: 'Maroon',
  removeIconClass: 'fas fa-times',
  image: 'Image',
  productName: 'Product Name',
  productPrice: 'Price',
  productQuantity: 'Quantity',
  remove: 'Remove',
  totalProductPrice: 'Total Price',
  totalCartPrice: 'Your Total :$',
  continueShopping: 'Continue Shopping',
  stripeCheckoutKey:
    'pk_test_51IyhiTSAoPHzmNjVBMWYDdC09jqqR0QKSRQXJTR5XncbGUsHd3EV8OoETxnF5VIDGW92FdIJOI2SneZ4wbQgmHYe00bhLttufU',
  categoryElectronics: 'electronics',
  brandHeader: 'Brand :',
  priceLabel: 'Price :',
  colourLabel: 'Colours :',
  valueLabelDisplay: 'auto',
  arialabelledby: 'range-slider',
  maxPrice: '2000',
  stepPriceSlider: '50',
  categoryMen: 'men',
  categoryWomen: 'women',
  menProductLink: `/products/${'mens'}`,
  womenProductLink: `/products/${'womens'}`,
  electronicsProductLink: `/products/${'electronics'}`,
  error: 'error',
  varientDanger: 'danger',
  shoppingCartIcon: 'fas fa-shopping-cart',
  description: 'Description',
  tabId: 'uncontrolled-tab-example',
  specification: 'Specification',
  relatedProducts: 'Related Products :',
  trashIcon: 'fas fa-trash',
  plusIcon: 'fas fa-plus',
  carouselClassname: 'd-block w-100',
  formControlComponent: 'fieldset',
  formLabel: 'legend',
  slimFitCottonShirtId: 'm1',
  slimFitCottonShirtName: 'Slim Fit Cotton Shirt',
  cottonPoloShirtId: 'm2',
  cottonPoloShirtName: 'Cotton Polo Shirt',
  clothingDescription: `The Model is wearing one from our stylist's collection, see the image for a mock-up of what the actual item would look like.it has text written on it in a black cursive language which looks great on a white color.`,
  slimFitCottonShirtImage:
    'http://themes.pixelstrap.com/multikart/assets/images/pro3/28.jpg',
  cottonPoloShirtImage:
    'http://themes.pixelstrap.com/multikart/assets/images/pro3/33.jpg',
  fitShirtId: 'm3',
  fitShirtName: 'Fit Shirt',
  shortSleeveId: 'm4',
  shortSleeveName: `Men Short Sleeve T-Shirt`,
  adidasMenTshitId: 'm5',
  adidasTshitName: `Adidas  Regular T-Shirt`,
  adidasMenTshitImage: 'https://m.media-amazon.com/images/I/31+UkA6owzL.jpg',
  cottonShirtWomenId: 'w1',
  cottonShirtWomenImage:
    'http://themes.pixelstrap.com/multikart/assets/images/pro3/2.jpg',
  poloWomenShirtId: 'w2',
  poloWomenShirtName: ` Women's Cotton Polo Shirt`,
  poloWomenShirtImage:
    'http://themes.pixelstrap.com/multikart/assets/images/pro3/1.jpg',

  pinkShirtId: 'w3',
  pinkShirtName: 'Women Pink SHIRT',
  pinkShirtImage:
    'https://m.media-amazon.com/images/I/61hbqL0V5JL._AC_UL320_.jpg',
  womenSleeveShirtId: 'w4',
  womenSleeveShirtName: `Women's Short Sleeve T-Shirt`,
  womenSleeveShirtImage:
    'https://m.media-amazon.com/images/I/81PBvVoAUyL._AC_UL320_.jpg',
  womenAdidasShirtId: 'w5',
  womenAdidasShirtImage:
    'https://m.media-amazon.com/images/I/614rKOTHPLL._AC_UL320_.jpg',
  wirelessMouseId: 'e1',
  wirelessMouseName: 'Wireless Mouse',
  wirelessMouseDescription: `Reliable Wireless Connection : Enjoy a wireless connection up to 10m away thanks to a plug-and-forget USB mini-receiver`,
  wirelessMouseImage: 'https://m.media-amazon.com/images/I/31N2n4tGvGL.jpg',
  routerId: 'e1',
  routerName: ' TP-Link AC750 Dual Band Wireless Cable Router',
  routerDescription: `750 Mbps Dual Band Wi-Fi —— Simultaneous 2.4GHz 300Mbps and 5GHz 433Mbps connections for 733Mbps of total available bandwidth`,
  routerImage: 'https://m.media-amazon.com/images/I/61uvEaXUcyL._AC_UL320_.jpg',
  keyBoardId: 'e3',
  keyboardName: ' Wireless Keyboard Mouse',
  keyboardDescription: `Give your workspace a modern appearance with a stylish wireless keyboard and mouse. A slim profile with silver accents perfectly complements your PC or tablet, while the wireless design creates a clean look. Extended battery : life Confidently work for long periods with a highly efficient keyboard and mouse featuring long battery life, Battery Type: 2AAA, 1AA`,
  keyboardImage:
    'https://m.media-amazon.com/images/I/61d4mVumQhL._AC_UL320_.jpg',
  webcamId: 'e4',
  webcamName: `HD WEBCAM`,
  webcamDescription: `Full HD widescreen video calling: Logitech C270 let you make widescreen video calls in HD 720p at 30fps. The lense with 60-degree field of view covers all of the action.HD lighting adjustment: Automatically improves the warmth and balance of your image for whatever setting you are in, so you look your best, even in dim environments`,
  webcamImage: 'https://m.media-amazon.com/images/I/61yo4swj-PL._AC_UL320_.jpg',
  deskpadId: 'e5',
  deskpadName: `Leather Desk Pad`,
  deskpadDescription: `100% ORIGINAL LEATHER : All IKARUS products made of premium quality 100% original full grain LEATHER. Full-Grain Leather is the top layer of the animal skins which is the most expensive and durable. The distinguishing feature of this leather is 100% natural & as every hide is having its own character there may be some natural effects, Two Tone (i.e. shade of two colors), Original leather grain, and leathers are made through about 11-14 complete process to get a quality outcome.`,
  deskpadImage:
    'https://m.media-amazon.com/images/I/81k70vmCg9S._AC_UL320_.jpg',
};
export default constants;
